### ISSUE TITLE
(xolidosigndesktop) Broken stuck after install test

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/Chocolatey-packages#2]

**Comment by tunisiano187** [comment]
Try to add a Autohotkey file

**Comment by tunisiano187** [comment]
Yes, working on other more importants

Le jeu. 16 juil. 2020 à 22:48, stale[bot] <notifications@github.com> a
écrit :

**Comment by tunisiano187** [comment]
https://github.com/chocolatey-community/chocolatey-package-requests/issues/864

**Comment by chtof** [comment]
https://github.com/chocolatey-community/chocolatey-test-environment

Tt should be nice if you can have a Chocolatey Test environment. It allows to test a package in the same conditions than the package verifier. For example, this Chocolatey package currently fails due to a missing dependency on .NET framework.
