### ISSUE TITLE
xolidosigndesktop v2.2.1.47 Failed Verification Testing

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/Chocolatey-packages#7]

**Comment by tunisiano187** [comment]
Duplicate of #2

**Comment by chtof** [comment]
https://github.com/chocolatey-community/chocolatey-test-environment

Tt should be nice if you can have a Chocolatey Test environment. It allows to test a package in the same conditions than the package verifier. For example, this Chocolatey package currently fails due to a missing dependency on .NET framework.

**Comment by tunisiano187** [comment]
Yes, i just don't have any computer available for it, as i'm using hyper-v for many things and hyper-v and virtualbox can't coexist...
But thank for the reminder
